// Mock AI generation function that returns lorem ipsum paragraphs
export async function mockGenerateAIResponse(): Promise<string[]> {
	return [
		'It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.',
		'The Karenin household was in complete disarray that morning, as if some invisible force had descended upon it, scattering the normal rhythms of life to the four winds. The servants moved about with unusual haste, their faces betraying a mixture of curiosity and apprehension, while Anna Arkadyevna herself remained sequestered in her chambers, having taken breakfast alone for the third consecutive day.',
		"Prince Andrei gazed out across the vast expanse of the battlefield, his mind curiously detached from the chaos that surrounded him. The smoke from the cannons hung heavy in the air, obscuring the horizon and lending an otherworldly quality to the scene before him. Men moved like specters through this artificial fog, their uniforms no longer distinguishing friend from foe, their humanity reduced to mere silhouettes against the backdrop of war's terrible canvas.",
		"Natasha could not sleep that night. The moonlight streamed through her window, casting long shadows across the wooden floor of her bedroom, and her thoughts turned inevitably to the ball that awaited her the following evening. She rose from her bed and approached the mirror, studying her features with the critical eye of a young woman on the precipice of society's embrace, wondering if she would be found wanting.",
		'The Moscow winter had settled in with unforgiving ferocity, transforming the city into a landscape of pristine white and bitter cold. The Rostov family, like many others of their station, had withdrawn into the warm cocoon of their estate, where the crackling fires and thick walls provided sanctuary from the howling winds that swept through the streets outside.',
		'Pierre Bezukhov found himself, not for the first time, questioning the purpose of his existence as he wandered through the crowded ballroom. The chandeliers above cast their golden light upon the assembled nobility, their jewels and finery sparkling with ostentatious brilliance, while conversations ebbed and flowed around him like the tide, touching upon everything and nothing of consequence.',
		'The countryside stretched out before Levin like a living painting, the fields of wheat swaying gently in the summer breeze, the distant forest a dark line against the horizon. Here, away from the artificial constraints of society, he felt a sense of peace that had eluded him in Moscow, a connection to something larger and more meaningful than the endless social machinations that occupied the minds of his peers.',
		'Countess Marya Bolkonskaya knelt in prayer, her forehead pressed against the cool stone floor of the chapel, her lips moving in silent supplication. The icon of the Virgin gazed down upon her with eternal compassion, the flickering candlelight lending animation to the painted face, creating the illusion of understanding in those ancient eyes that had witnessed centuries of human suffering and joy.',
		'The drawing room of the Shcherbatsky house was filled with the gentle murmur of conversation and the occasional burst of laughter. Kitty moved among the guests with practiced grace, her heart heavy despite the smile fixed upon her face. She caught sight of Vronsky across the room, his attention focused entirely on Anna, and felt the sharp sting of rejection anew, though she maintained her composure with the discipline expected of a young woman of her breeding.',
		'The battle of Borodino loomed on the horizon like an approaching storm, its inevitability weighing heavily upon the minds of officers and common soldiers alike. Around the campfires, men spoke in hushed tones of home and family, of the lives they had left behind and hoped to return to, their words carrying the poignant awareness that many would not live to see another sunset.',
		"Dolly Oblonsky surveyed the chaos of her household with resigned acceptance, the children's toys scattered across the floor, the marks of small fingers on the furniture, the general disarray that accompanied the joyful tumult of family life. She had long since abandoned the pursuit of perfection, finding instead a different kind of satisfaction in the beautiful mess that surrounded her, a testament to the life she had created despite the challenges of her marriage.",
		"The grand ball at the Governor's mansion was the event of the season, drawing nobility from across the province, all eager to see and be seen in the glittering assembly. The orchestra played a waltz, the music swelling and filling the vast ballroom, while couples moved across the polished floor in perfect synchrony, a living demonstration of society's carefully choreographed dance.",
		'Nikolai Rostov rode across his estate, the rhythmic hoofbeats of his horse a counterpoint to his troubled thoughts. The land stretched out around him, fields and forests that had belonged to his family for generations, now threatened by the mounting debts that seemed to grow with each passing season. The responsibility of preserving this inheritance weighed upon him like a physical burden, shaping his decisions and narrowing his choices.',
		'The drawing room fell silent as Count Bezukhov entered, his imposing figure commanding attention without effort. Age had not diminished his presence; if anything, the silver in his hair and the lines etched into his face by time only added to the aura of authority that surrounded him. The younger members of the gathering watched him with a mixture of respect and curiosity, aware that they were in the presence of a man who had witnessed the turning of an era.',
		'Anna watched the countryside flash past the window of the train, each revolution of the wheels carrying her further from Moscow'
	];
}
